server:
  port: 8081

spring:
  application:
    name: service_profile
   #Todo: Config Database
  datasource:
    url: jdbc:mysql://localhost:3306/s_profile
    username: root
    password: rootuser@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
  show-sql: true


#Todo: Config swagger
springdoc:
  swagger-ui.path: /profile-swagger-ui.html
  #http://192.168.0.104:8080/swagger-ui/index.html

##Todo: Config Eureka
#eureka:
#  client:
#    service-url.defaultZone: http://localhost:8761/eureka
##    register-with-eureka: true
##    fetch-registry: true

