server:
  port: 8084
spring:
  application:
    name: service_payment

  #After: We will using Docker-compose file
  datasource:
    url: jdbc:mysql://localhost:3306/s_payment
    username: root
    password: rootuser@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  #      ddl-auto: update
  show-sql: true

springdoc:
  swagger-ui.path: /payment-swagger-ui.html

  #http://192.168.0.104:8080/swagger-ui/index.html
#
##Todo: Config Logging
#logging:
#  config: classpath:log4j2-spring.yaml
#     #Spring Boot automatically exposes application.yaml properties as system properties when the application runs.
#    #For Log4j2 to pick this up, ensure that the logging.file.name property is loaded as a system property.
#
#  level:
#    root: INFO
#  file.name: logs/service_payment_logs/service_payment_dev_env.log   #Setup path save file-logging




