server.port: 8083

spring:
  application:
    name: order-service
    #Todo: Config Database
  datasource:
    url: jdbc:mysql://localhost:3306/s_order
    username: root
    password: rootuser@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
  show-sql: true


#Todo: config Eureka-Client can known the url of Eureka-Server
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl.defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true


#Todo: Config swagger
springdoc:
  swagger-ui.path: /order-swagger-ui.html